import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToasterContext from "@/context/ToasterContext";
import AuthWrapper from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cooking Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-orange-50" lang="en">
      <body className={inter.className}>
        <AuthWrapper>
          <ToasterContext />
          {children}
        </AuthWrapper>
      </body>
    </html>
  );
}
